'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'HI';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Core Translations Dictionary
const TRANSLATIONS: Record<Language, Record<string, string>> = {
  EN: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.howWeWork': 'How We Work',
    'nav.contact': 'Contact',
    'nav.registerAdvisor': 'Register as Advisor',
    'nav.signIn': 'Sign In',
    'nav.bookConsultation': 'Book Consultation',
    'nav.trustedPlatform': 'Trusted Advisory Platform',
    'nav.discoverCatalog': 'Discover Catalog',
    'nav.myConsultations': 'My Consultations',
    'nav.advisorWorkspace': 'Advisor Workspace',
    'nav.adminSuite': 'Admin Suite',

    // Hero Section
    'hero.badge': 'Trusted by 10,000+ Indians for Legal & Property Consultation',
    'hero.title': 'Secure Professional Consultations via',
    'hero.titleGold': 'Escrow Protection',
    'hero.subtitle': 'Connect with RERA-verified brokers, high-experience legal advisors, wealth managers, and documentation experts. Safe, secure, and fully verified.',
    'hero.searchPlaceholder': 'Search legal advisors, RERA brokers, tax consultants...',
    'hero.popular': 'Popular:',
    'hero.tax': 'Tax',
    'hero.corporate': 'Corporate',
    'hero.rera': 'RERA',
    'hero.court': 'Court',

    // Services Catalog
    'services.title': 'Verified Advisory Services',
    'services.subtitle': 'Explore our catalog of highly-vetted advisors across core domains. Book instant audio/video appointments.',
    
    // Stats Section
    'stats.advisors': 'Verified Advisors',
    'stats.consultations': 'Consultations Done',
    'stats.rating': 'Success Rating',
    'stats.escrow': 'Escrow Protection',

    // How it works
    'how.title': 'How BrokerSaab Works',
    'how.subtitle': 'Book with confidence knowing your money is held in escrow until your consultation is completed successfully.',
    'how.step1.title': '1. Choose an Expert',
    'how.step1.desc': 'Browse RERA-verified brokers, BAR-registered lawyers, and certified advisors.',
    'how.step2.title': '2. Reserve Slot via Escrow',
    'how.step2.desc': 'Pay securely. The money is held safely in escrow and is not released immediately.',
    'how.step3.title': '3. Connect & Release',
    'how.step3.desc': 'Have your consultation via video/audio. Once satisfied, release funds to the advisor.',

    // Footer
    'footer.description': "India's trusted marketplace connecting users with verified legal advisors, property brokers, financial consultants, and documentation experts.",
    'footer.rights': 'All Rights Reserved.',
    'footer.securityDesc': 'All transactions are protected by bank-grade escrow technology. Advisors are verified manually.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.legal': 'Legal',

    // Terms & Conditions clauses (shared)
    'tc.fraud.title': 'No Liability for Fraud or Misconduct',
    'tc.fraud.body': 'BrokerSaab is a third-party technology marketplace. We are NOT responsible or liable for any fraudulent activity, misrepresentation, negligence, professional misconduct, or financial harm caused by any advisor, agent, or dealer on this platform. Users engage professionals entirely at their own risk.',
    'tc.dispute.title': 'Disputes — Indian Judiciary',
    'tc.dispute.body': 'All disputes, claims, or legal proceedings arising from use of BrokerSaab or from any transaction between a user and an advisor shall be subject exclusively to the jurisdiction of the competent courts of India. BrokerSaab shall not be a party to such disputes.',
    'tc.escrow.title': 'Escrow Payment Protection',
    'tc.escrow.body': 'Payments are held in escrow and released to advisors only upon consultation completion. While escrow protects your funds, BrokerSaab does NOT guarantee the quality, accuracy, or outcome of any professional advice or service rendered.',
    'tc.userResp.title': 'User Responsibilities',
    'tc.userResp.body': "You are responsible for independently verifying the credentials, qualifications, and suitability of any professional before acting on their advice. BrokerSaab's internal verification is not a government certification and does not substitute your own due diligence.",
    'tc.platform.title': 'Platform Role',
    'tc.platform.body': 'BrokerSaab acts as a neutral intermediary only. No advisor-client relationship, fiduciary duty, or professional liability is created with BrokerSaab. The platform may suspend accounts that violate conduct policies without prior notice.',
    'tc.govLaw': 'Governing Law:',
    'tc.govLawText': 'These terms are governed by the laws of the Republic of India. Any legal disputes shall be exclusively subject to the jurisdiction of the courts of India. BrokerSaab shall not be a party to any dispute between users and advisors.',
    'tc.effective': 'Effective Date: June 2026 · BrokerSaab Technology Pvt. Ltd.',
    'tc.important': 'Important:',
    'tc.importantText': 'By using BrokerSaab, you acknowledge that you have read, understood, and agree to all the terms below. These terms govern your use of the platform.',
    'tc.scrollHint': '↓ Scroll down to read all terms before accepting',
    'tc.agreeText': 'I have read and I agree to the Terms & Conditions, including that BrokerSaab is not liable for fraud or misconduct by advisors, and all disputes are subject to Indian courts.',
    'tc.acceptBtn': 'I Accept — Continue to Sign In',

    // Auth / Login flow
    'auth.terms.title': 'Terms & Conditions',
    'auth.terms.sub': 'Please read and accept before continuing',
    'auth.phone.title': 'Sign In to Continue',
    'auth.phone.sub': 'Enter your mobile number to get started',
    'auth.phone.label': 'Mobile Number',
    'auth.phone.placeholder': '10-digit mobile number',
    'auth.phone.sendOtp': 'Send OTP',
    'auth.phone.sending': 'Sending…',
    'auth.phone.backTerms': '← Back to Terms',
    'auth.otp.title': 'Verify Your Number',
    'auth.otp.label': 'Enter 6-digit OTP',
    'auth.otp.verify': 'Verify OTP',
    'auth.otp.verifying': 'Verifying…',
    'auth.otp.changePhone': '← Change phone number',
    'auth.register.title': 'Complete Your Profile',
    'auth.register.sub': 'Tell us your name to personalise your experience',
    'auth.register.nameLabel': 'Full Name',
    'auth.register.namePlaceholder': 'Your full name',
    'auth.register.emailLabel': 'Email Address',
    'auth.register.emailOptional': '(optional)',
    'auth.register.createBtn': 'Create Account',
    'auth.register.creating': 'Creating account…',
    'auth.password.title': 'Secure Your Account',
    'auth.password.sub': 'Set a password for faster logins next time',
    'auth.password.info': 'A password lets you skip OTP next time and log in instantly. You can always switch back to OTP login.',
    'auth.password.newLabel': 'New Password',
    'auth.password.confirmLabel': 'Confirm Password',
    'auth.password.placeholder': 'Min 8 chars, upper + lower + number',
    'auth.password.repeatPlaceholder': 'Repeat your password',
    'auth.password.setBtn': 'Set Password',
    'auth.password.setting': 'Setting password…',
    'auth.password.skip': 'Skip for now — I\'ll use OTP next time →',
    'auth.password.yourPwd': 'Your password',
    'auth.success.title': "You're All Set!",
    'auth.success.signedIn': "You're signed in!",
    'auth.success.welcomeText': 'Welcome to BrokerSaab! Taking you to services…',
    'auth.success.advisorText': 'Welcome back, Advisor. Redirecting to your dashboard…',
    'auth.adminLogin': 'Admin / Advisor Login',
    'auth.orText': 'or',
    'auth.otpLogin': '📲 OTP Login',
    'auth.pwdLogin': '🔒 Password Login',
    'auth.login': 'Login',
    'auth.loggingIn': 'Logging in…',
    'auth.getOtp': 'Get OTP',
    'auth.mobileNumber': 'Mobile Number',
    'auth.password': 'Password',
    'auth.enterPhone': 'Enter 10-digit number',
    'auth.sending': 'Sending OTP...',
    'auth.verifying': 'Verifying...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.savingPwd': 'Saving Password…',
    'auth.setPwdContinue': 'Set Password & Continue',
    'auth.skipOtp': 'Skip for now — I\'ll use OTP login',
    'auth.completeReg': 'Complete Registration',
    'auth.exploreServices': 'Explore Services',
    'auth.myConsultations': 'My Consultations',
    'auth.goToDashboard': 'Go to My Dashboard',
    'auth.passwordsMatch': '✓ Passwords match',
    'auth.passwordsNoMatch': '✗ Passwords do not match',
    'auth.pwdReq.chars': '8+ chars',
    'auth.pwdReq.upper': 'Uppercase',
    'auth.pwdReq.lower': 'Lowercase',
    'auth.pwdReq.number': 'Number',

    // Advisor Onboarding
    'onboard.title': 'Advisor Registration',
    'onboard.sub': 'Join thousands of verified advisors on BrokerSaab',
    'onboard.cancel': 'Are you sure you want to cancel the onboarding registration? Any unsaved progress will be lost.',
    'onboard.welcome.heading': 'Become a Verified Advisor',
    'onboard.welcome.sub': 'Join BrokerSaab and start earning from your expertise — completely free to register.',
    'onboard.welcome.howTitle': 'How It Works',
    'onboard.welcome.step1Title': 'Fill your professional profile',
    'onboard.welcome.step1Desc': 'Share your name, license, fees, and expertise in a few minutes.',
    'onboard.welcome.step2Title': 'Select your service categories',
    'onboard.welcome.step2Desc': 'Choose the legal or financial services you specialise in.',
    'onboard.welcome.step3Title': 'Set your availability',
    'onboard.welcome.step3Desc': 'Pick the days and hours you are available for consultations.',
    'onboard.welcome.step4Title': 'Submit for admin review',
    'onboard.welcome.step4Desc': 'Our team verifies credentials and goes live within 24–48 hours.',
    'onboard.welcome.reqTitle': 'Requirements',
    'onboard.welcome.req1': 'Active phone number & email',
    'onboard.welcome.req2': 'At least one service category',
    'onboard.welcome.req3': 'Professional bio (50+ characters)',
    'onboard.welcome.req4': 'License number (optional but recommended)',
    'onboard.welcome.benTitle': 'Benefits',
    'onboard.welcome.ben1': 'Earn consultation fees directly',
    'onboard.welcome.ben2': 'Set your own flexible hours',
    'onboard.welcome.ben3': 'Verified badge builds trust',
    'onboard.welcome.ben4': 'Escrow-protected payments',
    'onboard.welcome.tcTitle': 'Advisor Terms & Conditions',
    'onboard.welcome.tcMust': 'Must accept to proceed',
    'onboard.welcome.tcScrollHint': '↓ Scroll to read all advisor terms before accepting',
    'onboard.welcome.tcAgree': 'I have read and accept the Advisor Terms & Conditions, including that BrokerSaab is not liable for fraud or misconduct, disputes are under Indian courts, and all my submitted documents are genuine and accurate.',
    'onboard.welcome.acceptBtn': 'I Accept — Start Registration',
    'onboard.welcome.acceptTermsBtn': 'Accept Terms to Continue',
    'onboard.adv.noLiability.title': 'No Platform Liability for Fraud or Misbehaviour',
    'onboard.adv.noLiability.body': 'BrokerSaab is a third-party technology marketplace. The platform is NOT liable for any fraudulent activity, misrepresentation, negligence, or professional misconduct by any advisor listed on the platform — including you.',
    'onboard.adv.disputes.title': 'Disputes — Indian Judiciary',
    'onboard.adv.disputes.body': 'All disputes, complaints, or proceedings arising from your advisory services or your use of BrokerSaab shall be subject exclusively to the jurisdiction of the competent courts of India.',
    'onboard.adv.docAuth.title': 'Document Authenticity & Accuracy',
    'onboard.adv.docAuth.body': 'You confirm that all KYC documents, license information, qualifications, and professional credentials submitted to BrokerSaab are genuine, current, and accurate.',
    'onboard.adv.indResp.title': 'Independent Professional Responsibility',
    'onboard.adv.indResp.body': 'You are solely responsible for the quality, accuracy, and legality of all advice, services, and documents you provide to clients. BrokerSaab does not supervise, endorse, or guarantee your advice.',
    'onboard.adv.commission.title': 'Platform Commission & Conduct',
    'onboard.adv.commission.body': 'BrokerSaab deducts a 15% service commission from all completed consultation payments. You agree to maintain professional conduct, honour confirmed bookings, and not solicit clients to transact outside the platform.',
    'onboard.adv.govLaw': 'Governing Law:',
    'onboard.adv.govLawText': 'These terms are governed by the laws of the Republic of India. BrokerSaab will fully cooperate with Indian law enforcement in any investigation of fraud, forgery, or misconduct.',
    'onboard.otp.title': 'Verify Your Mobile Number',
    'onboard.otp.sub': "We'll send a 6-digit OTP to confirm your number.",
    'onboard.otp.phoneLabel': 'Mobile Number',
    'onboard.otp.sendOtp': 'Send OTP',
    'onboard.otp.enterOtp': 'Enter 6-digit OTP',
    'onboard.otp.verifyOtp': 'Verify OTP',
    'onboard.otp.resend': 'Resend OTP',
    'onboard.otp.resendIn': 'Resend in ',
    'onboard.otp.sending': 'Sending…',
    'onboard.otp.verifying': 'Verifying…',
    'onboard.otp.verified': 'Verified!',
    'onboard.otp.verifiedSub': 'Your mobile number is confirmed.',
    'onboard.otp.welcomeBack': 'Welcome back!',
    'onboard.otp.stoppedAt': 'You previously stopped at',
    'onboard.otp.resumeQ': 'Would you like to continue where you left off?',
    'onboard.otp.continueFrom': 'Continue from',
    'onboard.otp.startFresh': 'Start Fresh',
    'onboard.type.title': 'Select Advisor Type',
    'onboard.type.sub': 'Choose the type of advisor profile you want to create.',
    'onboard.account.title': 'Account Details',
    'onboard.account.sub': 'Set up your login credentials.',
    'onboard.account.emailLabel': 'Email Address *',
    'onboard.account.pwdLabel': 'Password *',
    'onboard.account.confirmPwdLabel': 'Confirm Password *',
    'onboard.profile.title': 'Professional Profile',
    'onboard.profile.sub': 'Tell clients about your expertise.',
    'onboard.profile.nameLabel': 'Full Name *',
    'onboard.profile.bizNameLabel': 'Business / Firm Name',
    'onboard.profile.expLabel': 'Years of Experience *',
    'onboard.profile.stateLabel': 'State *',
    'onboard.profile.cityLabel': 'City / Area *',
    'onboard.profile.circleLabel': 'Circle / Taluka',
    'onboard.profile.subdivLabel': 'Sub-division / Village',
    'onboard.profile.feeLabel': 'Consultation Fee (₹) per session',
    'onboard.profile.langLabel': 'Languages *',
    'onboard.profile.langPlaceholder': 'Type a language and press Enter',
    'onboard.profile.bioLabel': 'Professional Bio *',
    'onboard.profile.licenseLabel': 'License Number',
    'onboard.profile.gstLabel': 'GST Number (optional)',
    'onboard.kyc.title': 'KYC Verification',
    'onboard.kyc.sub': 'Upload your identity documents for verification.',
    'onboard.kyc.aadhaarLabel': 'Aadhaar Card *',
    'onboard.kyc.aadhaarNumLabel': 'Aadhaar Number *',
    'onboard.kyc.consentLabel': 'I consent to Aadhaar data processing for KYC verification.',
    'onboard.kyc.photoLabel': 'Passport-size Photo *',
    'onboard.kyc.licenseLabel': 'License Copy *',
    'onboard.kyc.gstLabel': 'GST Certificate (optional)',
    'onboard.kyc.consentNotice': 'Aadhaar Data Security Notice (UIDAI / Aadhaar Act 2016): Your Aadhaar number is stored only as an irreversible one-way cryptographic hash — it cannot be recovered or read by anyone, including BrokerSaab staff. Only the last 4 digits are stored in readable form for identity confirmation. Your data is processed exclusively for KYC verification in compliance with Government of India regulations.',
    'onboard.kyc.consentCheckbox': 'I consent to Aadhaar data processing as described above',
    'onboard.kyc.uploadAadhaar': 'Upload Aadhaar card (JPG, PNG or PDF, max 5 MB)',
    'onboard.kyc.uploadPhoto': 'Upload your photo (JPG or PNG, max 5 MB)',
    'onboard.kyc.uploadLicense': 'Upload license document (JPG, PNG or PDF, max 5 MB)',
    'onboard.kyc.uploadGstCert': 'Upload GST certificate (JPG, PNG or PDF, max 5 MB) — optional',
    'onboard.kyc.licenseNumLabel': 'License Number *',
    'onboard.kyc.gstNumLabel': 'GST Number (optional)',
    'onboard.services.title': 'Service Categories',
    'onboard.services.sub': 'Select the categories you specialise in.',
    'onboard.avail.title': 'Weekly Availability',
    'onboard.avail.sub': 'Set the days and times you are available for consultations.',
    'onboard.review.title': 'Review & Submit',
    'onboard.review.sub': 'Review your information before submitting.',
    'onboard.review.confirmText': 'I confirm that all the information provided is accurate and complete to the best of my knowledge.',
    'onboard.review.confirmTextFull': "I confirm that all the above information is accurate and authentic. I agree to BrokerSaab's Advisor Terms and understand that providing false information may lead to immediate account suspension.",
    'onboard.review.submitBtn': 'Submit Application',
    'onboard.review.submitting': 'Submitting…',
    'onboard.review.printBtn': 'Print / Download PDF',
    'onboard.review.creatingAccount': 'Creating account…',
    'onboard.review.proceedPayment': 'Proceed to Payment',
    'onboard.review.submitVerification': 'Submit for Verification',
    'onboard.payment.title': 'Complete Payment to Submit',
    'onboard.payment.sub': 'Your application will be submitted only after payment is confirmed.',
    'onboard.success.title': 'Profile Submitted!',
    'onboard.success.sub': 'Our team will review your credentials and get back to you within 24–48 hours.',
    'onboard.success.whatsNext': 'What Happens Next',
    'onboard.success.step1Title': 'Profile Review (24–48h)',
    'onboard.success.step1Desc': 'Our team verifies your license number and credentials.',
    'onboard.success.step2Title': 'Email Confirmation',
    'onboard.success.step2Desc': 'You receive a notification once your profile is approved.',
    'onboard.success.step3Title': 'Go Live',
    'onboard.success.step3Desc': 'Your profile appears on BrokerSaab and clients can book you.',
    'onboard.success.saveApp': 'Save Your Application',
    'onboard.success.printApp': 'Print Application',
    'onboard.success.downloadPdf': 'Download PDF',
    'onboard.success.printHint': 'Opens print dialog — choose "Save as PDF" to download',
    'onboard.success.exploreServices': 'Explore BrokerSaab',
    'onboard.success.advisorLogin': 'Advisor Login',
    'onboard.btn.next': 'Next',
    'onboard.btn.back': 'Back',
    'onboard.btn.continue': 'Continue',
    'onboard.btn.skip': 'Skip for Now',
    'onboard.btn.review': 'Review',
    'onboard.progress.verify': 'Verify',
    'onboard.progress.type': 'Type',
    'onboard.progress.account': 'Account',
    'onboard.progress.profile': 'Profile',
    'onboard.progress.kyc': 'KYC',
    'onboard.progress.services': 'Services',
    'onboard.progress.availability': 'Availability',
    'onboard.progress.review': 'Review',

    // Contact / Support page
    'contact.pageTitle': 'Support & Contact',
    'contact.status.open': 'Open',
    'contact.status.inProgress': 'In Progress',
    'contact.status.resolved': 'Resolved',
    'contact.status.closed': 'Closed',
    'contact.priority.low': 'Low',
    'contact.priority.medium': 'Medium',
    'contact.priority.high': 'High',
    'contact.priority.urgent': 'Urgent',
    'contact.category.general': 'General',
    'contact.category.billing': 'Billing',
    'contact.category.technical': 'Technical',
    'contact.category.bookingIssue': 'Booking Issue',
    'contact.category.advisorIssue': 'Advisor Issue',
    'contact.category.other': 'Other',
    'contact.newTicket': 'New Ticket',
    'contact.subject': 'Subject',
    'contact.category': 'Category',
    'contact.priority': 'Priority',
    'contact.description': 'Description',
    'contact.submit': 'Submit Ticket',
    'contact.submitting': 'Submitting…',
    'contact.activity.assigned': 'Ticket assigned',
    'contact.activity.closed': 'Ticket closed',
    'contact.pageSub': 'Raise and track support tickets',
    'contact.signInTitle': 'Sign in to access support',
    'contact.signInSub': 'Create tickets and track their resolution from your account.',
    'contact.signInBtn': 'Sign In',
    'contact.loggedInAs': 'Logged in as',
    'contact.yourTickets': 'Your support tickets',
    'contact.raiseTicket': 'Raise Ticket',
    'contact.myTickets': 'My Tickets',
    'contact.loading': 'Loading…',
    'contact.noTickets': 'No tickets yet',
    'contact.raiseHint': 'Click "Raise Ticket" to get help.',
    'contact.subjectPlaceholder': 'Brief description of your issue',
    'contact.descPlaceholder': 'Describe your issue in detail…',
    'contact.priorityLabel': 'Priority',
    'contact.closingNotes': 'Closing Notes',
    'contact.activityTimeline': 'Activity Timeline',
    'contact.raisedOn': 'Raised',
    'contact.selectOrRaise': 'Select a ticket or raise a new one',
    'contact.requiredError': 'Subject and description are required.',
    'contact.networkError': 'Network error. Please try again.',
    'contact.failedSubmit': 'Failed to submit ticket.'
  },
  HI: {
    // Navbar
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.services': 'सेवाएं',
    'nav.howWeWork': 'काम कैसे करता है',
    'nav.contact': 'संपर्क करें',
    'nav.registerAdvisor': 'सलाहकार के रूप में पंजीकरण करें',
    'nav.signIn': 'लॉग इन करें',
    'nav.bookConsultation': 'परामर्श बुक करें',
    'nav.trustedPlatform': 'विश्वसनीय सलाहकार मंच',
    'nav.discoverCatalog': 'कैटलॉग खोजें',
    'nav.myConsultations': 'मेरे परामर्श',
    'nav.advisorWorkspace': 'सलाहकार कार्यक्षेत्र',
    'nav.adminSuite': 'एडमिन सूट',

    // Hero Section
    'hero.badge': 'कानूनी और संपत्ति परामर्श के लिए 10,000+ भारतीयों द्वारा विश्वसनीय',
    'hero.title': 'सुरक्षित पेशेवर परामर्श प्राप्त करें',
    'hero.titleGold': 'एस्क्रो सुरक्षा के साथ',
    'hero.subtitle': 'RERA-सत्यापित दलालों, अनुभवी कानूनी सलाहकारों, धन प्रबंधकों और दस्तावेज़ीकरण विशेषज्ञों से जुड़ें। सुरक्षित और पूरी तरह से सत्यापित।',
    'hero.searchPlaceholder': 'कानूनी सलाहकार, RERA दलाल, कर सलाहकार खोजें...',
    'hero.popular': 'लोकप्रिय:',
    'hero.tax': 'टैक्स',
    'hero.corporate': 'कॉर्पोरेट',
    'hero.rera': 'RERA',
    'hero.court': 'कोर्ट',

    // Services Catalog
    'services.title': 'सत्यापित सलाहकार सेवाएं',
    'services.subtitle': 'मुख्य क्षेत्रों में हमारे अत्यधिक सत्यापित सलाहकारों के कैटलॉग का अन्वेषण करें। तुरंत ऑडियो/वीडियो अपॉइंटमेंट बुक करें।',

    // Stats Section
    'stats.advisors': 'सत्यापित सलाहकार',
    'stats.consultations': 'परामर्श संपन्न',
    'stats.rating': 'सफलता दर',
    'stats.escrow': 'एस्क्रो सुरक्षा',

    // How it works
    'how.title': 'ब्रोकरसाब कैसे काम करता है',
    'how.subtitle': 'विश्वास के साथ बुक करें यह जानते हुए कि आपका पैसा परामर्श सफलतापूर्वक पूरा होने तक सुरक्षित एस्क्रो में रखा जाता है।',
    'how.step1.title': '1. एक विशेषज्ञ चुनें',
    'how.step1.desc': 'RERA-सत्यापित दलालों, बार-पंजीकृत वकीलों और प्रमाणित सलाहकारों को खोजें।',
    'how.step2.title': '2. एस्क्रो के माध्यम से स्लॉट आरक्षित करें',
    'how.step2.desc': 'सुरक्षित रूप से भुगतान करें। पैसा सुरक्षित रूप से एस्क्रो में रखा जाता है और तुरंत जारी नहीं किया जाता है।',
    'how.step3.title': '3. जुड़ें और जारी करें',
    'how.step3.desc': 'वीडियो/ऑडियो के माध्यम से अपना परामर्श लें। संतुष्ट होने पर, सलाहकार को धनराशि जारी करें।',

    // Footer
    'footer.description': "भारत का विश्वसनीय बाज़ार जो उपयोगकर्ताओं को सत्यापित कानूनी सलाहकारों, संपत्ति दलालों, वित्तीय सलाहकारों और दस्तावेज़ीकरण विशेषज्ञों से जोड़ता है।",
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.securityDesc': 'सभी लेनदेन बैंक-ग्रेड एस्क्रो तकनीक द्वारा सुरक्षित हैं। सलाहकारों का सत्यापन मैन्युअल रूप से किया जाता है।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.services': 'हमारी सेवाएं',
    'footer.legal': 'कानूनी',

    // Terms & Conditions clauses (shared)
    'tc.fraud.title': 'धोखाधड़ी या दुर्व्यवहार के लिए कोई दायित्व नहीं',
    'tc.fraud.body': 'ब्रोकरसाब एक तृतीय-पक्ष प्रौद्योगिकी बाज़ार है। हम इस प्लेटफ़ॉर्म पर किसी भी सलाहकार, एजेंट या डीलर द्वारा की गई किसी भी धोखाधड़ी, गलत बयानी, लापरवाही, पेशेवर दुर्व्यवहार या वित्तीय नुकसान के लिए उत्तरदायी नहीं हैं। उपयोगकर्ता पूरी तरह से अपने जोखिम पर पेशेवरों से जुड़ते हैं।',
    'tc.dispute.title': 'विवाद — भारतीय न्यायपालिका',
    'tc.dispute.body': 'ब्रोकरसाब के उपयोग से उत्पन्न सभी विवाद, दावे या कार्यवाही विशेष रूप से भारत के सक्षम न्यायालयों के अधिकार क्षेत्र के अधीन होंगे। ब्रोकरसाब ऐसे विवादों का पक्ष नहीं होगा।',
    'tc.escrow.title': 'एस्क्रो भुगतान सुरक्षा',
    'tc.escrow.body': 'भुगतान एस्क्रो में रखा जाता है और परामर्श पूरा होने पर ही सलाहकार को जारी किया जाता है। एस्क्रो आपके धन की रक्षा करता है, लेकिन ब्रोकरसाब किसी भी पेशेवर सलाह या सेवा की गुणवत्ता, सटीकता या परिणाम की गारंटी नहीं देता।',
    'tc.userResp.title': 'उपयोगकर्ता की जिम्मेदारियां',
    'tc.userResp.body': 'आप किसी भी पेशेवर की सलाह पर काम करने से पहले उनकी योग्यताओं, क्रेडेंशियल्स और उपयुक्तता की स्वतंत्र रूप से जांच करने के लिए जिम्मेदार हैं। ब्रोकरसाब का आंतरिक सत्यापन सरकारी प्रमाणन नहीं है।',
    'tc.platform.title': 'प्लेटफ़ॉर्म की भूमिका',
    'tc.platform.body': 'ब्रोकरसाब केवल एक तटस्थ मध्यस्थ के रूप में कार्य करता है। प्लेटफ़ॉर्म का उपयोग करने से ब्रोकरसाब के साथ कोई सलाहकार-ग्राहक संबंध, प्रत्ययी कर्तव्य या व्यावसायिक दायित्व नहीं बनता।',
    'tc.govLaw': 'शासी कानून:',
    'tc.govLawText': 'ये शर्तें भारत गणराज्य के कानूनों द्वारा शासित हैं। सभी कानूनी विवाद विशेष रूप से भारत के न्यायालयों के अधिकार क्षेत्र के अधीन होंगे।',
    'tc.effective': 'प्रभावी तिथि: जून 2026 · ब्रोकरसाब टेक्नोलॉजी प्रा. लि.',
    'tc.important': 'महत्वपूर्ण:',
    'tc.importantText': 'ब्रोकरसाब का उपयोग करके, आप स्वीकार करते हैं कि आपने नीचे दी गई सभी शर्तें पढ़ी, समझी और उनसे सहमत हैं।',
    'tc.scrollHint': '↓ स्वीकार करने से पहले सभी शर्तें पढ़ें',
    'tc.agreeText': 'मैंने शर्तें और नियम पढ़े हैं और मैं सहमत हूँ, जिसमें यह शामिल है कि ब्रोकरसाब सलाहकारों द्वारा धोखाधड़ी के लिए जिम्मेदार नहीं है, और सभी विवाद भारतीय न्यायालयों के अधीन हैं।',
    'tc.acceptBtn': 'मैं स्वीकार करता/करती हूँ — साइन इन करें',

    // Auth / Login flow
    'auth.terms.title': 'शर्तें और नियम',
    'auth.terms.sub': 'जारी रखने से पहले कृपया पढ़ें और स्वीकार करें',
    'auth.phone.title': 'जारी रखने के लिए साइन इन करें',
    'auth.phone.sub': 'शुरू करने के लिए अपना मोबाइल नंबर दर्ज करें',
    'auth.phone.label': 'मोबाइल नंबर',
    'auth.phone.placeholder': '10 अंकों का मोबाइल नंबर',
    'auth.phone.sendOtp': 'OTP भेजें',
    'auth.phone.sending': 'भेजा जा रहा है…',
    'auth.phone.backTerms': '← शर्तों पर वापस',
    'auth.otp.title': 'अपना नंबर सत्यापित करें',
    'auth.otp.label': '6-अंकीय OTP दर्ज करें',
    'auth.otp.verify': 'OTP सत्यापित करें',
    'auth.otp.verifying': 'सत्यापित हो रहा है…',
    'auth.otp.changePhone': '← फ़ोन नंबर बदलें',
    'auth.register.title': 'अपनी प्रोफ़ाइल पूरी करें',
    'auth.register.sub': 'अपना अनुभव व्यक्तिगत बनाने के लिए अपना नाम बताएं',
    'auth.register.nameLabel': 'पूरा नाम',
    'auth.register.namePlaceholder': 'आपका पूरा नाम',
    'auth.register.emailLabel': 'ईमेल पता',
    'auth.register.emailOptional': '(वैकल्पिक)',
    'auth.register.createBtn': 'खाता बनाएं',
    'auth.register.creating': 'खाता बनाया जा रहा है…',
    'auth.password.title': 'अपने खाते को सुरक्षित करें',
    'auth.password.sub': 'अगली बार तेज़ लॉगिन के लिए पासवर्ड सेट करें',
    'auth.password.info': 'पासवर्ड से आप अगली बार OTP के बिना तुरंत लॉगिन कर सकते हैं। आप OTP लॉगिन पर भी वापस जा सकते हैं।',
    'auth.password.newLabel': 'नया पासवर्ड',
    'auth.password.confirmLabel': 'पासवर्ड की पुष्टि करें',
    'auth.password.placeholder': 'न्यूनतम 8 अक्षर, बड़े + छोटे + अंक',
    'auth.password.repeatPlaceholder': 'पासवर्ड दोबारा दर्ज करें',
    'auth.password.setBtn': 'पासवर्ड सेट करें',
    'auth.password.setting': 'पासवर्ड सेट हो रहा है…',
    'auth.password.skip': 'अभी छोड़ें — मैं OTP उपयोग करूंगा/करूंगी →',
    'auth.password.yourPwd': 'आपका पासवर्ड',
    'auth.success.title': 'सब तैयार है!',
    'auth.success.signedIn': 'आप साइन इन हैं!',
    'auth.success.welcomeText': 'ब्रोकरसाब में आपका स्वागत है! सेवाओं की ओर ले जा रहे हैं…',
    'auth.success.advisorText': 'वापसी पर स्वागत है, सलाहकार। आपके डैशबोर्ड पर ले जा रहे हैं…',
    'auth.adminLogin': 'एडमिन / सलाहकार लॉगिन',
    'auth.orText': 'या',
    'auth.otpLogin': '📲 OTP लॉगिन',
    'auth.pwdLogin': '🔒 पासवर्ड लॉगिन',
    'auth.login': 'लॉगिन करें',
    'auth.loggingIn': 'लॉगिन हो रहा है…',
    'auth.getOtp': 'OTP प्राप्त करें',
    'auth.mobileNumber': 'मोबाइल नंबर',
    'auth.password': 'पासवर्ड',
    'auth.enterPhone': '10 अंकों का नंबर दर्ज करें',
    'auth.sending': 'OTP भेजा जा रहा है...',
    'auth.verifying': 'सत्यापित हो रहा है...',
    'auth.creatingAccount': 'खाता बनाया जा रहा है...',
    'auth.savingPwd': 'पासवर्ड सहेजा जा रहा है…',
    'auth.setPwdContinue': 'पासवर्ड सेट करें और जारी रखें',
    'auth.skipOtp': 'अभी छोड़ें — मैं OTP लॉगिन करूंगा/करूंगी',
    'auth.completeReg': 'पंजीकरण पूरा करें',
    'auth.exploreServices': 'सेवाएं खोजें',
    'auth.myConsultations': 'मेरे परामर्श',
    'auth.goToDashboard': 'मेरे डैशबोर्ड पर जाएं',
    'auth.passwordsMatch': '✓ पासवर्ड मेल खाते हैं',
    'auth.passwordsNoMatch': '✗ पासवर्ड मेल नहीं खाते',
    'auth.pwdReq.chars': '8+ अक्षर',
    'auth.pwdReq.upper': 'बड़ा अक्षर',
    'auth.pwdReq.lower': 'छोटा अक्षर',
    'auth.pwdReq.number': 'अंक',

    // Advisor Onboarding
    'onboard.title': 'सलाहकार पंजीकरण',
    'onboard.sub': 'ब्रोकरसाब पर हज़ारों सत्यापित सलाहकारों से जुड़ें',
    'onboard.cancel': 'क्या आप वाकई ऑनबोर्डिंग पंजीकरण रद्द करना चाहते हैं? कोई भी न सहेजी गई प्रगति खो जाएगी।',
    'onboard.welcome.heading': 'सत्यापित सलाहकार बनें',
    'onboard.welcome.sub': 'ब्रोकरसाब से जुड़ें और अपनी विशेषज्ञता से कमाई शुरू करें — पंजीकरण पूरी तरह निःशुल्क है।',
    'onboard.welcome.howTitle': 'यह कैसे काम करता है',
    'onboard.welcome.step1Title': 'अपनी पेशेवर प्रोफ़ाइल भरें',
    'onboard.welcome.step1Desc': 'कुछ मिनटों में अपना नाम, लाइसेंस, शुल्क और विशेषज्ञता साझा करें।',
    'onboard.welcome.step2Title': 'अपनी सेवा श्रेणियां चुनें',
    'onboard.welcome.step2Desc': 'उन कानूनी या वित्तीय सेवाओं को चुनें जिनमें आप विशेषज्ञ हैं।',
    'onboard.welcome.step3Title': 'अपनी उपलब्धता सेट करें',
    'onboard.welcome.step3Desc': 'वे दिन और घंटे चुनें जब आप परामर्श के लिए उपलब्ध हैं।',
    'onboard.welcome.step4Title': 'समीक्षा के लिए जमा करें',
    'onboard.welcome.step4Desc': 'हमारी टीम 24-48 घंटों में आपकी प्रमाण-पत्रों की जांच करती है।',
    'onboard.welcome.reqTitle': 'आवश्यकताएं',
    'onboard.welcome.req1': 'सक्रिय फ़ोन नंबर और ईमेल',
    'onboard.welcome.req2': 'कम से कम एक सेवा श्रेणी',
    'onboard.welcome.req3': 'पेशेवर बायो (50+ अक्षर)',
    'onboard.welcome.req4': 'लाइसेंस नंबर (वैकल्पिक लेकिन अनुशंसित)',
    'onboard.welcome.benTitle': 'लाभ',
    'onboard.welcome.ben1': 'सीधे परामर्श शुल्क कमाएं',
    'onboard.welcome.ben2': 'अपने लचीले घंटे खुद सेट करें',
    'onboard.welcome.ben3': 'सत्यापित बैज विश्वास बनाता है',
    'onboard.welcome.ben4': 'एस्क्रो-संरक्षित भुगतान',
    'onboard.welcome.tcTitle': 'सलाहकार नियम और शर्तें',
    'onboard.welcome.tcMust': 'आगे बढ़ने के लिए स्वीकार करना होगा',
    'onboard.welcome.tcScrollHint': '↓ स्वीकार करने से पहले सभी सलाहकार शर्तें पढ़ें',
    'onboard.welcome.tcAgree': 'मैंने सलाहकार नियम और शर्तें पढ़ी और स्वीकार की हैं, जिसमें यह शामिल है कि ब्रोकरसाब धोखाधड़ी या दुर्व्यवहार के लिए उत्तरदायी नहीं है, विवाद भारतीय न्यायालयों के अधीन हैं, और मेरे सभी जमा किए गए दस्तावेज़ वास्तविक और सटीक हैं।',
    'onboard.welcome.acceptBtn': 'मैं स्वीकार करता/करती हूँ — पंजीकरण शुरू करें',
    'onboard.welcome.acceptTermsBtn': 'जारी रखने के लिए शर्तें स्वीकार करें',
    'onboard.adv.noLiability.title': 'धोखाधड़ी या दुर्व्यवहार के लिए कोई प्लेटफ़ॉर्म दायित्व नहीं',
    'onboard.adv.noLiability.body': 'ब्रोकरसाब एक तृतीय-पक्ष प्रौद्योगिकी बाज़ार है। प्लेटफ़ॉर्म आप सहित किसी भी सूचीबद्ध सलाहकार की किसी भी धोखाधड़ी, गलत बयानी, लापरवाही या पेशेवर दुर्व्यवहार के लिए उत्तरदायी नहीं है।',
    'onboard.adv.disputes.title': 'विवाद — भारतीय न्यायपालिका',
    'onboard.adv.disputes.body': 'आपकी सलाहकार सेवाओं या ब्रोकरसाब के आपके उपयोग से उत्पन्न सभी विवाद, शिकायतें या कार्यवाही विशेष रूप से भारत के सक्षम न्यायालयों के अधीन होंगी।',
    'onboard.adv.docAuth.title': 'दस्तावेज़ प्रामाणिकता और सटीकता',
    'onboard.adv.docAuth.body': 'आप पुष्टि करते हैं कि ब्रोकरसाब को जमा किए गए सभी KYC दस्तावेज़, लाइसेंस जानकारी, योग्यताएं और पेशेवर प्रमाण-पत्र वास्तविक, वर्तमान और सटीक हैं।',
    'onboard.adv.indResp.title': 'स्वतंत्र पेशेवर जिम्मेदारी',
    'onboard.adv.indResp.body': 'आप ग्राहकों को दी जाने वाली सभी सलाह, सेवाओं और दस्तावेज़ों की गुणवत्ता, सटीकता और कानूनीता के लिए पूरी तरह जिम्मेदार हैं। ब्रोकरसाब आपकी सलाह की निगरानी, समर्थन या गारंटी नहीं करता।',
    'onboard.adv.commission.title': 'प्लेटफ़ॉर्म कमीशन और आचरण',
    'onboard.adv.commission.body': 'ब्रोकरसाब सभी पूर्ण परामर्श भुगतानों से 15% सेवा कमीशन काटता है। आप व्यावसायिक आचरण बनाए रखने, पुष्टि की गई बुकिंग का सम्मान करने और ग्राहकों को प्लेटफ़ॉर्म के बाहर लेनदेन करने के लिए प्रेरित न करने पर सहमत हैं।',
    'onboard.adv.govLaw': 'शासी कानून:',
    'onboard.adv.govLawText': 'ये शर्तें भारत गणराज्य के कानूनों द्वारा शासित हैं। ब्रोकरसाब धोखाधड़ी, जालसाजी या दुर्व्यवहार की किसी भी जांच में भारतीय कानून प्रवर्तन के साथ पूरी तरह सहयोग करेगा।',
    'onboard.otp.title': 'अपना मोबाइल नंबर सत्यापित करें',
    'onboard.otp.sub': 'हम आपका नंबर पुष्टि करने के लिए 6-अंकीय OTP भेजेंगे।',
    'onboard.otp.phoneLabel': 'मोबाइल नंबर',
    'onboard.otp.sendOtp': 'OTP भेजें',
    'onboard.otp.enterOtp': '6-अंकीय OTP दर्ज करें',
    'onboard.otp.verifyOtp': 'OTP सत्यापित करें',
    'onboard.otp.resend': 'OTP फिर से भेजें',
    'onboard.otp.resendIn': 'फिर से भेजें ',
    'onboard.otp.sending': 'भेजा जा रहा है…',
    'onboard.otp.verifying': 'सत्यापित हो रहा है…',
    'onboard.otp.verified': 'सत्यापित!',
    'onboard.otp.verifiedSub': 'आपका मोबाइल नंबर पुष्टि हो गया।',
    'onboard.otp.welcomeBack': 'वापसी पर स्वागत है!',
    'onboard.otp.stoppedAt': 'आप पहले इस चरण पर रुके थे:',
    'onboard.otp.resumeQ': 'क्या आप वहीं से जारी रखना चाहेंगे?',
    'onboard.otp.continueFrom': 'यहाँ से जारी रखें:',
    'onboard.otp.startFresh': 'नए सिरे से शुरू करें',
    'onboard.type.title': 'सलाहकार प्रकार चुनें',
    'onboard.type.sub': 'वह प्रकार चुनें जो आपकी प्रोफ़ाइल के लिए उपयुक्त है।',
    'onboard.account.title': 'खाता विवरण',
    'onboard.account.sub': 'अपने लॉगिन क्रेडेंशियल सेट करें।',
    'onboard.account.emailLabel': 'ईमेल पता *',
    'onboard.account.pwdLabel': 'पासवर्ड *',
    'onboard.account.confirmPwdLabel': 'पासवर्ड की पुष्टि करें *',
    'onboard.profile.title': 'पेशेवर प्रोफ़ाइल',
    'onboard.profile.sub': 'ग्राहकों को अपनी विशेषज्ञता के बारे में बताएं।',
    'onboard.profile.nameLabel': 'पूरा नाम *',
    'onboard.profile.bizNameLabel': 'व्यवसाय / फर्म का नाम',
    'onboard.profile.expLabel': 'अनुभव के वर्ष *',
    'onboard.profile.stateLabel': 'राज्य *',
    'onboard.profile.cityLabel': 'शहर / क्षेत्र *',
    'onboard.profile.circleLabel': 'सर्किल / तालुका',
    'onboard.profile.subdivLabel': 'उप-मंडल / गांव',
    'onboard.profile.feeLabel': 'परामर्श शुल्क (₹) प्रति सत्र',
    'onboard.profile.langLabel': 'भाषाएं *',
    'onboard.profile.langPlaceholder': 'भाषा टाइप करें और Enter दबाएं',
    'onboard.profile.bioLabel': 'पेशेवर बायो *',
    'onboard.profile.licenseLabel': 'लाइसेंस नंबर',
    'onboard.profile.gstLabel': 'GST नंबर (वैकल्पिक)',
    'onboard.kyc.title': 'KYC सत्यापन',
    'onboard.kyc.sub': 'सत्यापन के लिए अपने पहचान दस्तावेज़ अपलोड करें।',
    'onboard.kyc.aadhaarLabel': 'आधार कार्ड *',
    'onboard.kyc.aadhaarNumLabel': 'आधार नंबर *',
    'onboard.kyc.consentLabel': 'मैं KYC सत्यापन के लिए आधार डेटा प्रोसेसिंग की सहमति देता/देती हूँ।',
    'onboard.kyc.photoLabel': 'पासपोर्ट साइज फोटो *',
    'onboard.kyc.licenseLabel': 'लाइसेंस कॉपी *',
    'onboard.kyc.gstLabel': 'GST प्रमाण पत्र (वैकल्पिक)',
    'onboard.kyc.consentNotice': 'आधार डेटा सुरक्षा सूचना (UIDAI / आधार अधिनियम 2016): आपका आधार नंबर केवल एक अपरिवर्तनीय वन-वे क्रिप्टोग्राफ़िक हैश के रूप में संग्रहीत किया जाता है — इसे BrokerSaab स्टाफ सहित किसी के द्वारा भी पुनर्प्राप्त या पढ़ा नहीं जा सकता। पहचान पुष्टि के लिए केवल अंतिम 4 अंक पढ़ने योग्य रूप में संग्रहीत किए जाते हैं। आपका डेटा भारत सरकार के नियमों के अनुपालन में केवल KYC सत्यापन के लिए प्रोसेस किया जाता है।',
    'onboard.kyc.consentCheckbox': 'मैं ऊपर वर्णित आधार डेटा प्रोसेसिंग के लिए सहमति देता/देती हूँ',
    'onboard.kyc.uploadAadhaar': 'आधार कार्ड अपलोड करें (JPG, PNG या PDF, अधिकतम 5 MB)',
    'onboard.kyc.uploadPhoto': 'अपनी फोटो अपलोड करें (JPG या PNG, अधिकतम 5 MB)',
    'onboard.kyc.uploadLicense': 'लाइसेंस दस्तावेज़ अपलोड करें (JPG, PNG या PDF, अधिकतम 5 MB)',
    'onboard.kyc.uploadGstCert': 'GST प्रमाण पत्र अपलोड करें (JPG, PNG या PDF, अधिकतम 5 MB) — वैकल्पिक',
    'onboard.kyc.licenseNumLabel': 'लाइसेंस नंबर *',
    'onboard.kyc.gstNumLabel': 'GST नंबर (वैकल्पिक)',
    'onboard.services.title': 'सेवा श्रेणियां',
    'onboard.services.sub': 'वे श्रेणियां चुनें जिनमें आप विशेषज्ञ हैं।',
    'onboard.avail.title': 'साप्ताहिक उपलब्धता',
    'onboard.avail.sub': 'वे दिन और समय सेट करें जब आप परामर्श स्वीकार करते हैं।',
    'onboard.review.title': 'समीक्षा और जमा करें',
    'onboard.review.sub': 'जमा करने से पहले अपनी जानकारी की समीक्षा करें।',
    'onboard.review.confirmText': 'मैं पुष्टि करता/करती हूँ कि प्रदान की गई सभी जानकारी मेरी सर्वोत्तम जानकारी के अनुसार सटीक और पूर्ण है।',
    'onboard.review.confirmTextFull': 'मैं पुष्टि करता/करती हूँ कि ऊपर दी गई सभी जानकारी सटीक और प्रमाणिक है। मैं BrokerSaab की एडवाइजर शर्तों से सहमत हूँ और समझता/समझती हूँ कि गलत जानकारी देने पर खाता तुरंत निलंबित किया जा सकता है।',
    'onboard.review.submitBtn': 'आवेदन जमा करें',
    'onboard.review.submitting': 'जमा हो रहा है…',
    'onboard.review.printBtn': 'प्रिंट / PDF डाउनलोड करें',
    'onboard.review.creatingAccount': 'खाता बनाया जा रहा है…',
    'onboard.review.proceedPayment': 'भुगतान के लिए आगे बढ़ें',
    'onboard.review.submitVerification': 'सत्यापन के लिए जमा करें',
    'onboard.payment.title': 'जमा करने के लिए भुगतान पूरा करें',
    'onboard.payment.sub': 'भुगतान की पुष्टि होने के बाद ही आपका आवेदन जमा किया जाएगा।',
    'onboard.success.title': 'प्रोफ़ाइल जमा हो गई!',
    'onboard.success.sub': 'हमारी टीम आपके प्रमाणपत्रों की समीक्षा करेगी और 24–48 घंटों में आपसे संपर्क करेगी।',
    'onboard.success.whatsNext': 'आगे क्या होगा',
    'onboard.success.step1Title': 'प्रोफ़ाइल समीक्षा (24–48 घंटे)',
    'onboard.success.step1Desc': 'हमारी टीम आपके लाइसेंस नंबर और प्रमाणपत्रों की पुष्टि करती है।',
    'onboard.success.step2Title': 'ईमेल पुष्टिकरण',
    'onboard.success.step2Desc': 'आपकी प्रोफ़ाइल स्वीकृत होने पर आपको सूचना मिलेगी।',
    'onboard.success.step3Title': 'लाइव हो जाएं',
    'onboard.success.step3Desc': 'आपकी प्रोफ़ाइल BrokerSaab पर दिखेगी और ग्राहक आपको बुक कर सकेंगे।',
    'onboard.success.saveApp': 'अपना आवेदन सहेजें',
    'onboard.success.printApp': 'आवेदन प्रिंट करें',
    'onboard.success.downloadPdf': 'PDF डाउनलोड करें',
    'onboard.success.printHint': 'प्रिंट डायलॉग खुलेगा — डाउनलोड करने के लिए "Save as PDF" चुनें',
    'onboard.success.exploreServices': 'BrokerSaab एक्सप्लोर करें',
    'onboard.success.advisorLogin': 'एडवाइजर लॉगिन',
    'onboard.btn.next': 'अगला',
    'onboard.btn.back': 'पिछला',
    'onboard.btn.continue': 'जारी रखें',
    'onboard.btn.skip': 'अभी के लिए छोड़ें',
    'onboard.btn.review': 'समीक्षा करें',
    'onboard.progress.verify': 'सत्यापित',
    'onboard.progress.type': 'प्रकार',
    'onboard.progress.account': 'खाता',
    'onboard.progress.profile': 'प्रोफ़ाइल',
    'onboard.progress.kyc': 'KYC',
    'onboard.progress.services': 'सेवाएं',
    'onboard.progress.availability': 'उपलब्धता',
    'onboard.progress.review': 'समीक्षा',

    // Contact / Support page
    'contact.pageTitle': 'सहायता और संपर्क',
    'contact.status.open': 'खुला',
    'contact.status.inProgress': 'प्रगति में',
    'contact.status.resolved': 'हल किया गया',
    'contact.status.closed': 'बंद',
    'contact.priority.low': 'कम',
    'contact.priority.medium': 'मध्यम',
    'contact.priority.high': 'उच्च',
    'contact.priority.urgent': 'अत्यावश्यक',
    'contact.category.general': 'सामान्य',
    'contact.category.billing': 'बिलिंग',
    'contact.category.technical': 'तकनीकी',
    'contact.category.bookingIssue': 'बुकिंग समस्या',
    'contact.category.advisorIssue': 'सलाहकार समस्या',
    'contact.category.other': 'अन्य',
    'contact.newTicket': 'नई टिकट',
    'contact.subject': 'विषय',
    'contact.category': 'श्रेणी',
    'contact.priority': 'प्राथमिकता',
    'contact.description': 'विवरण',
    'contact.submit': 'टिकट जमा करें',
    'contact.submitting': 'जमा हो रहा है…',
    'contact.activity.assigned': 'टिकट असाइन की गई',
    'contact.activity.closed': 'टिकट बंद की गई',
    'contact.pageSub': 'सपोर्ट टिकट उठाएं और ट्रैक करें',
    'contact.signInTitle': 'सहायता तक पहुँचने के लिए साइन इन करें',
    'contact.signInSub': 'अपने खाते से टिकट बनाएं और उनके समाधान को ट्रैक करें।',
    'contact.signInBtn': 'साइन इन करें',
    'contact.loggedInAs': 'इस रूप में लॉग इन',
    'contact.yourTickets': 'आपके सपोर्ट टिकट',
    'contact.raiseTicket': 'टिकट उठाएं',
    'contact.myTickets': 'मेरे टिकट',
    'contact.loading': 'लोड हो रहा है…',
    'contact.noTickets': 'अभी तक कोई टिकट नहीं',
    'contact.raiseHint': 'सहायता के लिए "टिकट उठाएं" पर क्लिक करें।',
    'contact.subjectPlaceholder': 'अपनी समस्या का संक्षिप्त विवरण',
    'contact.descPlaceholder': 'अपनी समस्या का विस्तार से वर्णन करें…',
    'contact.priorityLabel': 'प्राथमिकता',
    'contact.closingNotes': 'समापन टिप्पणियां',
    'contact.activityTimeline': 'गतिविधि समयरेखा',
    'contact.raisedOn': 'उठाया गया',
    'contact.selectOrRaise': 'एक टिकट चुनें या नया उठाएं',
    'contact.requiredError': 'विषय और विवरण आवश्यक हैं।',
    'contact.networkError': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    'contact.failedSubmit': 'टिकट जमा करने में विफल।'
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('EN');

  // Load language preference from local storage if available
  useEffect(() => {
    const savedLanguage = localStorage.getItem('brokersaab_language') as Language;
    if (savedLanguage && (savedLanguage === 'EN' || savedLanguage === 'HI')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('brokersaab_language', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
